[package]
name = "latex"
version = "0.1.7"
edition = "2021"

[lib]
path = "src/latex.rs"
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4.40"
serde = "1.0.210"
serde_with = "3.11.0"
zed_extension_api = "0.1.0"
